name: kastela_sdk_dart
description: Kastela Client SDK for Dart / Flutter
version: 0.4.0
repository: https://github.com/kastela-sdp/kastela-sdk-dart
issue_tracker: https://github.com/kastela-sdp/kastela-sdk-dart/issues

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  pinenacl: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  graphql_flutter: ^5.1.2

flutter:
